name: Print Env

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: printenv | sort
        
