name: CI

on: 
  workflow_dispatch:
    inputs:
      instanceType:
        description: 'Runner instance type'
        required: true
        default: 'ubuntu-latest'

jobs:
  build:
    runs-on: ${{ github.event.inputs.instanceType }}
    steps:
      #- run: pidstat -h -u -d 1 100 > pidstat.csv &
      - run: pidstat -h -u -d 1 100 | grep -v -e "^$" | grep -v "UID" | awk '{ print $1 "," $3 "," $7 "," $9 "," $10 "," $13 }' > pidstat.csv &
      - run: date +%s > timing.dat
      - run: |
          echo "Instance Type: ${{ github.event.inputs.instanceType }}"
      - name: Countdown
        run: |
          $end = 30;
          $end..1 | % { Start-Sleep -s 1; Write-Host ""Countdown: $_"" }
        shell: pwsh
      - run: |
          date +%s >> timing.dat
          cat timing.dat
      - run: cat pidstat.csv
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          # Artifact name
          name: pidstat
          # A file, directory or wildcard pattern that describes what to upload
          path: pidstat.csv
          if-no-files-found: error
