name: CI

on: 
  workflow_dispatch:
    inputs:
      instanceType:
        description: 'Runner instance type'
        required: true
        default: 'ubuntu-latest'

jobs:
  build:
    runs-on: ${{ github.event.inputs.instanceType }}
    steps:
      - run: iostat -cxd 1 100 > iostat.csv &
      - run: |
          echo "Instance Type: ${{ github.event.inputs.instanceType }}"
      - name: Countdown
        run: |
          $end = 30;
          $end..1 | % { Start-Sleep -s 1; Write-Host ""Countdown: $_"" }
        shell: pwsh
      - run: cat iostat.csv
