name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Countdown
      run: |
        $end = 30;
        $end..1 | % { Start-Sleep -s 1; Write-Host ""Countdown: $_"" }
      shell: pwsh
