name: CI

on: 
  workflow_dispatch:
    inputs:
      instanceType:
        description: 'Runner instance type'
        required: true
        default: 'ubuntu-latest'

jobs:
  build:
    strategy:
      matrix:
        label: [label1, label2]
    runs-on: ${{ github.event.inputs.instanceType }}
    env:      
      artifactsDir: artifacts
      pidstatFile: artifacts/testing-${{ matrix.label }}-pidstat.txt
      timingFile: artifacts/testing-${{ matrix.label }}-timing.txt
    steps:
      - run: mkdir ${{ artifactsDir }}
      - run: pidstat -h -u -d 1 100 | grep -v -e "^$" | grep -v "UID" > ${{ env.pidstatFile }} &
      - run: date +%s > ${{ env.timingFile }}
      
      # Actual work goes here
      - run: |
          echo "Instance Type: ${{ github.event.inputs.instanceType }}"
      - name: Countdown
        run: |
          $end = 30;
          $end..1 | % { Start-Sleep -s 1; Write-Host ""Countdown: $_"" }
        shell: pwsh
      # End of actual work
      
      - run: date +%s >> ${{ env.timingFile }}
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: pidstat
          path: ${{ artifactsDir }}
          if-no-files-found: error
