name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        multiply: [Debug, Release, Windows]
    steps:
    - name: Countdown
      run: |
        $end = 3;
        $end..1 | % { Start-Sleep -s 1; Write-Host ""Countdown: $_"" }
      shell: pwsh
