name: CI

on: [push]

env:
  resourceGroup: ${{github.run_id}}${{github.run_number}}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo $resourceGroup
    - name: Run a one-line script
      run: echo "$resourceGroup"
    - name: Run a one-line script
      env:
        resourceGroup2: ${GITHUB_RUN_ID}${GITHUB_RUN_NUMBER}
      run: echo $resourceGroup2
