name: "Close stale issues"
on: push
 
jobs:
  stale:
    runs-on: self-hosted
    steps:
    - uses: pjquirk/stale@users/paquirk/v1ghesfixes
      env:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'So stale'
        stale-pr-message: 'So stale'
        days-before-stale: 0
        days-before-close: 0
